/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author warun
 */
public class Table extends javax.swing.JFrame {

	/**
	 * Creates new form Table
	 */
	public Table() {
		initComponents();
	}
	
	ArrayList<RequestQModel> queueList = new ArrayList<RequestQModel>();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setPreferredSize(new java.awt.Dimension(610, 500));
		setSize(new java.awt.Dimension(500, 1000));
		setLocation(new java.awt.Point(266, 0));
		ImageIcon logo = new ImageIcon(getClass().getClassLoader().getResource("queue2.png"));
		setIconImage(logo.getImage());
		setAlwaysOnTop(true);
		setTitle("รายการคิวที่เรียกไปแล้ว");
		setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N

		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		
		
		getContentPane().setLayout(null);

		jTable2.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
//		jTable2.setModel(
//		new javax.swing.table.DefaultTableModel(
//					new Object[][] { { "202", "เกียรติศักดิ์" }, { "203", "ศิวัช"},
//						 },
//					new String[] { "Number", "Name" 
//		}
//	)
//		{
//	public boolean isCellEditable(int row,int column) {
//	return false;
//		}
//		}
//
//
//);
		jScrollPane2.setViewportView(jTable2);

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(70, 20, 452, 402);
		
		
		
		dataTable();
//		Userqueue page1 = new Userqueue();
//		
//		Userqueue userqueue = new Userqueue();
//		jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
//		    @Override
//		    public void mouseClicked(java.awt.event.MouseEvent evt) {
//		        int row = jTable2.rowAtPoint(evt.getPoint());
//		        int col = jTable2.columnAtPoint(evt.getPoint());
//		        if (row >= 0 && col >= 0) {
//		          getData();
//
//		        }
//		    }
//		});
//		
		

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Table().setVisible(true);
			}
		});
	}
	
	public void getData() {
		int row2 = jTable2.getSelectedRow();
		String data = jTable2.getModel().getValueAt(row2,0).toString();
		System.out.println(data);
		
//		Userqueue page1 = new Userqueue();
//		page1.isVisible();
//		page1.setVisible(true);
//		page1.pack();
//		page1.jTextField2.setText(data);
		
	}
	
	
	public void dataTable() {
		
		Api api = new Api();
		
		jTable2.setModel(new DefaultTableModel());
		
		DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
		model.setNumRows(0);
		model.addColumn("Queue");
		model.addColumn("Name");
		model.addColumn(" ");
		model.addColumn("Room");
		queueList = api.requestQStatus();
		int row = 0;

		for (Iterator<RequestQModel> iterator = queueList.iterator(); iterator.hasNext();) {
			RequestQModel reqModel = (RequestQModel) iterator.next();
			model.addRow(new Object[0]);
			model.setValueAt(reqModel.getOqueue(), row, 0);
			model.setValueAt(reqModel.getPtname(), row, 1);
			model.setValueAt(" ",row,2);
			model.setValueAt(reqModel.getCurdep_name(), row, 3);
			row++;

		}

//		Connection connect = null;
//		PreparedStatement s = null;
//		ResultSet rs = null;
//
//		try {
//			try {
//				Class.forName("com.mysql.jdbc.Driver");
//			} catch (ClassNotFoundException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//
//			connect = DriverManager
//					.getConnection("jdbc:mysql://180.180.216.192:3306/db_ud12418"
//							+ "?user=ud12418&password=192168100250");
//    	   
//            String sql = "select vstdate,oqueue,hn from ovst where vstdate = curdate()" ;
//            s=connect.prepareStatement(sql);
//            rs = s.executeQuery();
            
//            int row=0;
//            while((rs!=null)&& (rs.next())) {
//            	model.addRow(new Object[0]);
//            	model.setValueAt(rs.getString("oqueue").toString(), row, 0);
//            	model.setValueAt(rs.getString("hn"), row, 1);
//            	row++;
//            }
//            
           
    
//    } catch (SQLException e ) {
//        JOptionPane.showMessageDialog(null, e);
//    }
//  
    }


	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable2;
	// End of variables declaration
}
